#!/usr/bin/env bash

export JENKINS_VERSION=lts
export GITLAB_VERSION=10.2.2
export NEXUS_VERSION=3.6.0
export SONAR_VERSION=5.6.7

export SMTP_HOST=${SMTP_HOST}

export JENKINS_SERVER_PORT=8180
export JENKINS_DATA_DIR=${JENKINS_DATA_DIR:-./data/jenkins/master}
export JENKINS_ADMIN_USER=${JENKINS_ADMIN_USER:-admin}
export JENKINS_ADMIN_PASS=${JENKINS_ADMIN_PASS:-admin}
export JENKINS_ADMIN_ADDR=${JENKINS_ADMIN_ADDR:-jenkins@example.com}
export JENKINS_REPLYTO_ADDR=${JENKINS_REPLYTO_ADDR:-${JENKINS_ADMIN_ADDR}}
export JENKINS_EMAIL_SUFFIX=${JENKINS_EMAIL_SUFFIX}
export JENKINS_IMAGE_VERSION=${JENKINS_IMAGE_VERSION:-1.0.0}
export JENKINS_EXECUTORS=${JENKINS_EXECUTORS:-4}
export JENKINS_GIT_NAME=${JENKINS_GIT_NAME:-jenkins}
export JENKINS_GIT_EMAIL=${JENKINS_GIT_EMAIL:-${JENKINS_ADMIN_ADDR}}
export JENKINS_SLAVE_AGENT_PORT=${JENKINS_SLAVE_AGENT_PORT:-50000}
export JENKINS_QUIET_PERIOD=${JENKINS_QUIET_PERIOD:-0}


export GITLAB_HTTP_PORT=${GITLAB_HTTP_PORT:-8280}
export GITLAB_SSH_PORT=${GITLAB_SSH_PORT:-8222}
export GITLAB_DB_DIR=${GITLAB_DATA_DIR:-./data/gitlab_db}
export GITLAB_REDIS_DIR=${GITLAB_DATA_DIR:-./data/gitlab_redis}
export GITLAB_DATA_DIR=${GITLAB_DATA_DIR:-./data/gitlab}

export NEXUS_DATA_DIR=${NEXUS_DATA_DIR:-./data/nexus}

export SONAR_DATA_DIR=${SONAR_DATA_DIR:-./data/sonar}
